//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpatialQueryInterface
{
    using System;
    using System.Collections.Generic;
    
    public partial class DLDYPL
    {
        public int OBJECTID { get; set; }
        public string WYID { get; set; }
        public string NAME { get; set; }
        public string DLDYQD { get; set; }
        public string DLDYZD { get; set; }
        public string DLDYMC { get; set; }
        public string DLWYID { get; set; }
        public string PQMC { get; set; }
    }
}
